name: CI_Build

on:
  push:
  pull_request:
    branches: [main]

env:
  VULKAN_SDK_VERSION: '1.3.296.0'

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release, Sanitizer]
    defaults:
      run:
        shell: pwsh -NoProfile {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: 'x64'

      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: ${{ env.VULKAN_SDK_VERSION }}
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true
          
      - name: Clear CMake Cache
        run: |
          if (Test-Path Build) {
            Remove-Item Build -Recurse -Force
          }

      - name: Build Dependencies (PHX)
        run: ./utils/build_lib_dependencies.ps1 -Config ${{ matrix.config }} -Architecture x64

      - name: Build Dependencies (Sample)
        run: ./utils/build_sample_dependencies.ps1 -Config ${{ matrix.config }} -Architecture x64

      - name: Generate Project
        run: cmake -B build -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config ${{ matrix.config }} --parallel
